{{- $needPgPassword := and (not .Values.global.existingSecret) (or .Values.database.bundled.enabled (not .Values.database.external.existingSecret)) -}}
{{- $needJwtKey := and (not .Values.global.existingSecret) (not .Values.config.existingSecret) -}}
{{- if or $needPgPassword $needJwtKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentregistry.fullname" . }}
  labels:
    {{- include "agentregistry.labels" . | nindent 4 }}
  {{- $annotations := include "agentregistry.annotations" (dict "annotations" dict "context" $) }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if $needPgPassword }}
  {{- if .Values.database.bundled.enabled }}
  POSTGRES_PASSWORD: {{ .Values.database.bundled.auth.password | toString | b64enc | quote }}
  {{- else }}
  POSTGRES_PASSWORD: {{ .Values.database.external.password | toString | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if $needJwtKey }}
  AGENT_REGISTRY_JWT_PRIVATE_KEY: {{ .Values.config.jwtPrivateKey | toString | b64enc | quote }}
  {{- end }}
{{- end }}
