# this workflow limits the number of open PRs created by a user
name: PR Limiter
on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]
  merge_group:
    types: [checks_requested]

permissions:
  pull-requests: write
  contents: read

jobs:
  pr-limiter:
    runs-on: ubuntu-latest
    steps:
    # only run this step on PRs, not in the merge queue (we need to explicitly add the merge queue logic because making this check required
    # causes it to get run in the merge queue as well)
    - name: Conditional skip for merge queue
      if: github.event_name == 'merge_group'
      run: |
        echo "Skipping check in merge queue"
        exit 0

    - if: github.event_name != 'merge_group'
      uses: Homebrew/actions/limit-pull-requests@master
      with:
        # https://docs.github.com/en/graphql/reference/enums#commentauthorassociation
        except-author-associations: |
          MEMBER
          OWNER
          COLLABORATOR
        comment-limit: 3
        comment: >
          You already have 3 pull requests open. Please consider working on getting
          the existing ones merged before opening new ones. Thanks!
