//go:build e2e

package kagent

import (
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

const e2eGenerateDocsEnv = "E2E_GEN_DOCS"

type e2eDocRecorder struct {
	b            strings.Builder
	replacements map[string]string
}

func newE2EDocRecorder(
	t *testing.T,
	outputPath string,
	title string,
	replacements map[string]string,
) *e2eDocRecorder {
	t.Helper()
	enabled, err := strconv.ParseBool(strings.TrimSpace(os.Getenv(e2eGenerateDocsEnv)))
	if err != nil || !enabled {
		return nil
	}
	recorder := &e2eDocRecorder{replacements: replacements}
	fmt.Fprintf(
		&recorder.b,
		"<!-- Code generated by OSS E2E tests; DO NOT EDIT. -->\n\n"+
			"# %s\n\n"+
			"## Run locally\n\n"+
			"Start the registry port-forward in a separate terminal:\n\n"+
			"```shell\n"+
			"kubectl --context \"kind-${KIND_CLUSTER_NAME:-agentregistry}\" -n \"${KIND_NAMESPACE:-agentregistry}\" port-forward svc/agentregistry 18121:12121\n"+
			"```\n\n"+
			"Set the scenario variables:\n\n"+
			"```shell\n"+
			"export KIND_CLUSTER_NAME=\"${KIND_CLUSTER_NAME:-agentregistry}\"\n"+
			"export KIND_NAMESPACE=\"${KIND_NAMESPACE:-agentregistry}\"\n"+
			"export KAGENT_NAMESPACE=\"${KAGENT_NAMESPACE:-kagent}\"\n"+
			"export E2E_ID=\"${E2E_ID:-$(date +%%s)}\"\n"+
			"export ARCTL_API_BASE_URL=\"${ARCTL_API_BASE_URL:-http://localhost:18121/v0}\"\n"+
			"```\n",
		title,
	)
	t.Cleanup(func() {
		if t.Failed() {
			return
		}
		if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
			t.Errorf("create E2E documentation directory: %v", err)
			return
		}
		if err := os.WriteFile(outputPath, []byte(recorder.b.String()), 0o644); err != nil {
			t.Errorf("write E2E documentation: %v", err)
		}
	})
	return recorder
}

func (r *e2eDocRecorder) Step(title, description string) {
	if r == nil {
		return
	}
	fmt.Fprintf(&r.b, "\n## %s\n\n%s\n", title, description)
}

func (r *e2eDocRecorder) Apply(manifest string) {
	if r == nil {
		return
	}
	fmt.Fprintf(
		&r.b,
		"\n```shell\narctl apply -f - <<EOF\n%s\nEOF\n```\n",
		r.replace(strings.TrimSpace(manifest)),
	)
}

func (r *e2eDocRecorder) Command(command string) {
	if r == nil {
		return
	}
	fmt.Fprintf(&r.b, "\n```shell\n%s\n```\n", r.replace(strings.TrimSpace(command)))
}

func (r *e2eDocRecorder) replace(value string) string {
	keys := make([]string, 0, len(r.replacements))
	for key := range r.replacements {
		keys = append(keys, key)
	}
	slices.SortFunc(keys, func(a, b string) int {
		if len(a) == len(b) {
			return strings.Compare(a, b)
		}
		return len(b) - len(a)
	})
	for _, key := range keys {
		value = strings.ReplaceAll(value, key, r.replacements[key])
	}
	return value
}

func TestE2EDocRecorderWritesSuccessfulRun(t *testing.T) {
	t.Setenv(e2eGenerateDocsEnv, "true")
	outputPath := filepath.Join(t.TempDir(), "generated", "scenario.md")

	t.Run("record", func(t *testing.T) {
		docs := newE2EDocRecorder(
			t,
			outputPath,
			"Kagent lifecycle",
			map[string]string{"kagent-12345": "kagent-${E2E_ID}"},
		)
		docs.Step("Deploy runtime", "Create the runtime.")
		docs.Apply("apiVersion: ar.dev/v1alpha1\nkind: Runtime\nmetadata:\n  name: kagent-12345")
		docs.Command("arctl delete runtime kagent-12345")
	})

	content, err := os.ReadFile(outputPath)
	require.NoError(t, err)
	want := "<!-- Code generated by OSS E2E tests; DO NOT EDIT. -->\n\n" +
		"# Kagent lifecycle\n\n" +
		"## Run locally\n\n" +
		"Start the registry port-forward in a separate terminal:\n\n" +
		"```shell\n" +
		"kubectl --context \"kind-${KIND_CLUSTER_NAME:-agentregistry}\" -n \"${KIND_NAMESPACE:-agentregistry}\" port-forward svc/agentregistry 18121:12121\n" +
		"```\n\n" +
		"Set the scenario variables:\n\n" +
		"```shell\n" +
		"export KIND_CLUSTER_NAME=\"${KIND_CLUSTER_NAME:-agentregistry}\"\n" +
		"export KIND_NAMESPACE=\"${KIND_NAMESPACE:-agentregistry}\"\n" +
		"export KAGENT_NAMESPACE=\"${KAGENT_NAMESPACE:-kagent}\"\n" +
		"export E2E_ID=\"${E2E_ID:-$(date +%s)}\"\n" +
		"export ARCTL_API_BASE_URL=\"${ARCTL_API_BASE_URL:-http://localhost:18121/v0}\"\n" +
		"```\n\n" +
		"## Deploy runtime\n\n" +
		"Create the runtime.\n\n" +
		"```shell\n" +
		"arctl apply -f - <<EOF\n" +
		"apiVersion: ar.dev/v1alpha1\n" +
		"kind: Runtime\n" +
		"metadata:\n" +
		"  name: kagent-${E2E_ID}\n" +
		"EOF\n" +
		"```\n\n" +
		"```shell\n" +
		"arctl delete runtime kagent-${E2E_ID}\n" +
		"```\n"
	require.Equal(t, want, string(content))
}

func TestE2EDocRecorderDoesNothingWhenDisabled(t *testing.T) {
	t.Setenv(e2eGenerateDocsEnv, "false")
	outputPath := filepath.Join(t.TempDir(), "scenario.md")

	t.Run("record", func(t *testing.T) {
		docs := newE2EDocRecorder(t, outputPath, "Disabled", nil)
		docs.Step("Ignored", "No documentation should be written.")
		docs.Command("false")
	})

	_, err := os.Stat(outputPath)
	require.ErrorIs(t, err, os.ErrNotExist)
}
